/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlayerPhotoRouteImport } from './routes/playerPhoto'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumIndexRouteImport } from './routes/album.index'
import { Route as AlbumClassIdRouteImport } from './routes/album.$classId'
import { Route as AlbumTimeTeamIdRouteImport } from './routes/album.time.$teamId'
import { Route as AlbumJogadorPlayerIdRouteImport } from './routes/album.jogador.$playerId'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPhotoRoute = PlayerPhotoRouteImport.update({
  id: '/playerPhoto',
  path: '/playerPhoto',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIndexRoute = AlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumClassIdRoute = AlbumClassIdRouteImport.update({
  id: '/album/$classId',
  path: '/album/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumTimeTeamIdRoute = AlbumTimeTeamIdRouteImport.update({
  id: '/album/time/$teamId',
  path: '/album/time/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumJogadorPlayerIdRoute = AlbumJogadorPlayerIdRouteImport.update({
  id: '/album/jogador/$playerId',
  path: '/album/jogador/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/jogos': typeof JogosRoute
  '/playerPhoto': typeof PlayerPhotoRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/album/$classId': typeof AlbumClassIdRoute
  '/album/': typeof AlbumIndexRoute
  '/album/jogador/$playerId': typeof AlbumJogadorPlayerIdRoute
  '/album/time/$teamId': typeof AlbumTimeTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/jogos': typeof JogosRoute
  '/playerPhoto': typeof PlayerPhotoRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/album/$classId': typeof AlbumClassIdRoute
  '/album': typeof AlbumIndexRoute
  '/album/jogador/$playerId': typeof AlbumJogadorPlayerIdRoute
  '/album/time/$teamId': typeof AlbumTimeTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/jogos': typeof JogosRoute
  '/playerPhoto': typeof PlayerPhotoRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/album/$classId': typeof AlbumClassIdRoute
  '/album/': typeof AlbumIndexRoute
  '/album/jogador/$playerId': typeof AlbumJogadorPlayerIdRoute
  '/album/time/$teamId': typeof AlbumTimeTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/jogos'
    | '/playerPhoto'
    | '/quiz'
    | '/sitemap.xml'
    | '/sobre'
    | '/album/$classId'
    | '/album/'
    | '/album/jogador/$playerId'
    | '/album/time/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/jogos'
    | '/playerPhoto'
    | '/quiz'
    | '/sitemap.xml'
    | '/sobre'
    | '/album/$classId'
    | '/album'
    | '/album/jogador/$playerId'
    | '/album/time/$teamId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/jogos'
    | '/playerPhoto'
    | '/quiz'
    | '/sitemap.xml'
    | '/sobre'
    | '/album/$classId'
    | '/album/'
    | '/album/jogador/$playerId'
    | '/album/time/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  JogosRoute: typeof JogosRoute
  PlayerPhotoRoute: typeof PlayerPhotoRoute
  QuizRoute: typeof QuizRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AlbumClassIdRoute: typeof AlbumClassIdRoute
  AlbumIndexRoute: typeof AlbumIndexRoute
  AlbumJogadorPlayerIdRoute: typeof AlbumJogadorPlayerIdRoute
  AlbumTimeTeamIdRoute: typeof AlbumTimeTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playerPhoto': {
      id: '/playerPhoto'
      path: '/playerPhoto'
      fullPath: '/playerPhoto'
      preLoaderRoute: typeof PlayerPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/': {
      id: '/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AlbumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$classId': {
      id: '/album/$classId'
      path: '/album/$classId'
      fullPath: '/album/$classId'
      preLoaderRoute: typeof AlbumClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/time/$teamId': {
      id: '/album/time/$teamId'
      path: '/album/time/$teamId'
      fullPath: '/album/time/$teamId'
      preLoaderRoute: typeof AlbumTimeTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/jogador/$playerId': {
      id: '/album/jogador/$playerId'
      path: '/album/jogador/$playerId'
      fullPath: '/album/jogador/$playerId'
      preLoaderRoute: typeof AlbumJogadorPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  JogosRoute: JogosRoute,
  PlayerPhotoRoute: PlayerPhotoRoute,
  QuizRoute: QuizRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AlbumClassIdRoute: AlbumClassIdRoute,
  AlbumIndexRoute: AlbumIndexRoute,
  AlbumJogadorPlayerIdRoute: AlbumJogadorPlayerIdRoute,
  AlbumTimeTeamIdRoute: AlbumTimeTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
